backend:
  name: github
  repo: rocket-monkey/jur-gatsby

media_folder: static/img
public_folder: /img

collections:
  - name: 'blog'
    label: 'Blog'
    folder: 'src/pages/blog'
    create: true
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
    fields:
      - {
          label: 'Template Key',
          name: 'templateKey',
          widget: 'hidden',
          default: 'blog-post',
        }
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Publish Date', name: 'date', widget: 'datetime' }
      - { label: 'Description', name: 'description', widget: 'text' }
      - { label: 'Body', name: 'body', widget: 'markdown' }
      - { label: 'Tags', name: 'tags', widget: 'list' }

  - name: 'pages'
    label: 'Pages'
    files:
      - file: 'src/pages/home/index.md'
        label: 'Home'
        name: 'home'
        fields:
          - {
              label: 'Template Key',
              name: 'templateKey',
              widget: 'hidden',
              default: 'home-page',
            }
          - { label: 'Title', name: 'title', widget: 'string' }
          - { label: 'Body', name: 'body', widget: 'markdown' }

      - file: 'src/pages/spirit/index.md'
        label: 'Spirit'
        name: 'spirit'
        fields:
          - {
              label: 'Template Key',
              name: 'templateKey',
              widget: 'hidden',
              default: 'spirit-page',
            }
          - { label: 'Title', name: 'title', widget: 'string' }
          - {
              name: image,
              label: 'Hero Image',
              widget: image,
              media_library: { config: { multiple: false } },
            }
          - { label: 'Body', name: 'body', widget: 'markdown' }

      - file: 'src/pages/wear/index.md'
        label: 'Wear'
        name: 'wear'
        fields:
          - {
              label: 'Template Key',
              name: 'templateKey',
              widget: 'hidden',
              default: 'wear-page',
            }
          - { label: 'Title', name: 'title', widget: 'string' }
          - { label: 'Body', name: 'body', widget: 'markdown' }

      - file: 'src/pages/eventArchive/index.md'
        label: 'Event Archiv'
        name: 'eventArchive'
        fields:
          - {
              label: 'Template Key',
              name: 'templateKey',
              widget: 'hidden',
              default: 'eventArchive-page',
            }
          - { label: 'Title', name: 'title', widget: 'string' }
          - { label: 'Body', name: 'body', widget: 'markdown' }
          - name: flyers
            label: 'Flyers'
            widget: list
            required: false
            fields:
              - { label: Label, name: label, required: false }
              - {
                  name: image,
                  label: Image,
                  widget: image,
                  media_library: { config: { multiple: false } },
                }

      - file: 'src/pages/store/index.md'
        label: 'Store'
        name: 'store'
        fields:
          - {
              label: 'Template Key',
              name: 'templateKey',
              widget: 'hidden',
              default: 'store-page',
            }
          - { label: 'Title', name: 'title', widget: 'string' }
          - { label: 'Facebook Link', name: 'fbLink', widget: 'string' }
          - {
              name: image,
              label: 'Hero Image',
              widget: image,
              media_library: { config: { multiple: false } },
            }
          - { label: 'Body', name: 'body', widget: 'markdown' }
