backend:
  name: github
  repo: rocket-monkey/hair-core

media_folder: static/img
public_folder: /img

collections:
  - name: 'blog'
    label: 'Blog'
    folder: 'src/pages/blog'
    create: true
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
    fields:
      - {
          label: 'Template Key',
          name: 'templateKey',
          widget: 'hidden',
          default: 'blog-post',
        }
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Publish Date', name: 'date', widget: 'datetime' }
      - { label: 'Description', name: 'description', widget: 'text' }
      - { label: 'Body', name: 'body', widget: 'markdown' }
      - { label: 'Tags', name: 'tags', widget: 'list' }

  - name: 'product'
    label: 'Product'
    folder: 'src/pages/product'
    create: true
    fields:
      - {
          label: 'Template Key',
          name: 'templateKey',
          widget: 'hidden',
          default: 'product-post',
        }
      - { label: 'Title', name: 'title', widget: 'string' }
      - {
          name: image,
          label: 'Product Image',
          widget: image,
          media_library: { config: { multiple: false } },
        }
      - { label: 'Body', name: 'body', widget: 'markdown' }

  - name: 'testimonial'
    label: 'Testimonial'
    folder: 'src/pages/testimonial'
    create: true
    fields:
      - {
          label: 'Template Key',
          name: 'templateKey',
          widget: 'hidden',
          default: 'testimonial-post',
        }
      - { label: 'Title', name: 'title', widget: 'string' }
      - {
          name: image,
          label: 'Testimonial Image',
          widget: image,
          media_library: { config: { multiple: false } },
        }
      - { label: 'Body', name: 'body', widget: 'markdown' }

  - name: 'testimonial'
    label: 'Testimonial'
    folder: 'src/pages/testimonial'
    create: true
    fields:
      - {
          label: 'Template Key',
          name: 'templateKey',
          widget: 'hidden',
          default: 'testimonial-post',
        }
      - { label: 'Title', name: 'title', widget: 'string' }
      - {
          name: image,
          label: 'Product Image',
          widget: image,
          media_library: { config: { multiple: false } },
        }
      - { label: 'Body', name: 'body', widget: 'markdown' }

  - name: openingHours
    label: 'Opening Hours'
    folder: 'src/pages/openingHours'
    create: true
    fields:
      - {
          label: 'Template Key',
          name: 'templateKey',
          widget: 'hidden',
          default: 'openingHours-entry',
        }
      - { name: title, label: Day }
      - { name: hours, label: Hours, required: true }

  - name: holidays
    label: 'Holidays'
    folder: 'src/pages/holidays'
    create: true
    fields:
      - {
          label: 'Template Key',
          name: 'templateKey',
          widget: 'hidden',
          default: 'holidays-entry',
        }
      - { name: title, label: Title }
      - {
          name: from,
          label: Von,
          widget: 'date',
          default: '',
          format: 'DD.MM.YYYY',
          required: true,
        }
      - {
          name: to,
          label: Bis,
          widget: 'date',
          default: '',
          format: 'DD.MM.YYYY',
          required: true,
        }

  - name: 'images'
    label: 'Images'
    files:
      - file: 'src/pages/imagesStore/index.md'
        label: 'Store'
        name: 'store'
        fields:
          - {
              label: 'Template Key',
              name: 'templateKey',
              widget: 'hidden',
              default: 'images-store',
            }
          - { label: 'Title', name: 'title', widget: 'string' }
          - name: images
            label: 'Images'
            widget: list
            required: false
            fields:
              - { label: Label, name: label, required: false }
              - {
                  label: image,
                  name: Image,
                  widget: image,
                  media_library: { config: { multiple: false } },
                }

      - file: 'src/pages/imagesCustomers/index.md'
        label: 'Customers'
        name: 'customers'
        fields:
          - {
              label: 'Template Key',
              name: 'templateKey',
              widget: 'hidden',
              default: 'images-customers',
            }
          - { label: 'Title', name: 'title', widget: 'string' }
          - name: images
            label: 'Images'
            widget: list
            required: false
            fields:
              - { label: Label, name: label, required: false }
              - {
                  label: 'Type',
                  name: 'type',
                  widget: 'select',
                  options:
                    [
                      'cut-and-colors',
                      'extensions',
                      'semi-permanent-dreadlocks',
                      'hair-tattoos',
                    ],
                }
              - {
                  label: image,
                  name: Image,
                  widget: image,
                  media_library: { config: { multiple: false } },
                }

      - file: 'src/pages/imagesAbout/index.md'
        label: 'About'
        name: 'about'
        fields:
          - {
              label: 'Template Key',
              name: 'templateKey',
              widget: 'hidden',
              default: 'images-about',
            }
          - { label: 'Title', name: 'title', widget: 'string' }
          - name: images
            label: 'Images'
            widget: list
            required: false
            fields:
              - { label: Label, name: label, required: false }
              - {
                  label: image,
                  name: Image,
                  widget: image,
                  media_library: { config: { multiple: false } },
                }

      - file: 'src/pages/imagesGallery/index.md'
        label: 'Gallery'
        name: 'gallery'
        fields:
          - {
              label: 'Template Key',
              name: 'templateKey',
              widget: 'hidden',
              default: 'images-gallery',
            }
          - { label: 'Title', name: 'title', widget: 'string' }
          - name: images
            label: 'Images'
            widget: list
            required: false
            fields:
              - { label: Label, name: label, required: false }
              - {
                  label: image,
                  name: Image,
                  widget: image,
                  media_library: { config: { multiple: false } },
                }

  - name: 'pages'
    label: 'Pages'
    files:
      - file: 'src/pages/home/index.md'
        label: 'Home'
        name: 'home'
        fields:
          - {
              label: 'Template Key',
              name: 'templateKey',
              widget: 'hidden',
              default: 'home-page',
            }
          - { label: 'Title', name: 'title', widget: 'string' }
          - { label: 'Body', name: 'body', widget: 'markdown' }

      - file: 'src/pages/info/index.md'
        label: 'Home Info 🚨'
        name: 'info'
        fields:
          - {
              label: 'Template Key',
              name: 'templateKey',
              widget: 'hidden',
              default: 'info-page',
            }
          - { label: 'Title', name: 'title', widget: 'string' }
          - {
              label: 'Active',
              name: 'active',
              widget: 'boolean',
              default: false,
            }
          - { label: 'Body', name: 'body', widget: 'markdown' }

      - file: 'src/pages/about/index.md'
        label: 'About'
        name: 'about'
        fields:
          - {
              label: 'Template Key',
              name: 'templateKey',
              widget: 'hidden',
              default: 'about-page',
            }
          - { label: 'Title', name: 'title', widget: 'string' }
          - {
              name: image,
              label: 'Hero Image',
              widget: image,
              media_library: { config: { multiple: false } },
            }
          - { label: 'Body', name: 'body', widget: 'markdown' }

      - file: 'src/pages/kunsthaarPflegeanleitung/index.md'
        label: 'Kunsthaar Pflegeanleitung'
        name: 'kunsthaarPflegeanleitung'
        fields:
          - {
              label: 'Template Key',
              name: 'templateKey',
              widget: 'hidden',
              default: 'kunsthaarPflegeanleitung-page',
            }
          - { label: 'Title', name: 'title', widget: 'string' }
          - {
              name: image,
              label: 'Hero Image',
              widget: image,
              media_library: { config: { multiple: false } },
            }
          - { label: 'Body', name: 'body', widget: 'markdown' }

      - file: 'src/pages/prices/index.md'
        label: 'Prices'
        name: 'prices'
        fields:
          - {
              label: 'Template Key',
              name: 'templateKey',
              widget: 'hidden',
              default: 'prices-page',
            }
          - { label: 'Title', name: 'title', widget: 'string' }
          - {
              name: image,
              label: 'Hero Image',
              widget: image,
              media_library: { config: { multiple: false } },
              required: false,
            }
          - { label: 'Body', name: 'body', widget: 'markdown' }

      - file: 'src/pages/appointment/index.md'
        label: 'Appointment'
        name: 'appointment'
        fields:
          - {
              label: 'Template Key',
              name: 'templateKey',
              widget: 'hidden',
              default: 'appointment-page',
            }
          - { label: 'Title', name: 'title', widget: 'string' }
          - {
              name: image,
              label: 'Hero Image',
              widget: image,
              media_library: { config: { multiple: false } },
              required: false,
            }
          - { label: 'Body', name: 'body', widget: 'markdown' }
