backend:
  name: github
  repo: rocket-monkey/hair-core

media_folder: static/img
public_folder: /img

collections:
  - name: 'blog'
    label: 'Blog'
    folder: 'src/pages/blog'
    create: true
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
    fields:
      - {
          label: 'Template Key',
          name: 'templateKey',
          widget: 'hidden',
          default: 'blog-post',
        }
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Publish Date', name: 'date', widget: 'datetime' }
      - { label: 'Description', name: 'description', widget: 'text' }
      - { label: 'Body', name: 'body', widget: 'markdown' }
      - { label: 'Tags', name: 'tags', widget: 'list' }

  - name: 'pages'
    label: 'Pages'
    files:
      - file: 'src/pages/home/index.md'
        label: 'Home'
        name: 'home'
        fields:
          - {
              label: 'Template Key',
              name: 'templateKey',
              widget: 'hidden',
              default: 'home-page',
            }
          - { label: 'Title', name: 'title', widget: 'string' }
          - { label: 'Body', name: 'body', widget: 'markdown' }

      - file: 'src/pages/spirit/index.md'
        label: 'Spirit'
        name: 'spirit'
        fields:
          - {
              label: 'Template Key',
              name: 'templateKey',
              widget: 'hidden',
              default: 'spirit-page',
            }
          - { label: 'Title', name: 'title', widget: 'string' }
          - {
              name: image,
              label: 'Hero Image',
              widget: image,
              media_library: { config: { multiple: false } },
            }
          - { label: 'Body', name: 'body', widget: 'markdown' }

      - file: 'src/pages/store/index.md'
        label: 'Store'
        name: 'store'
        fields:
          - {
              label: 'Template Key',
              name: 'templateKey',
              widget: 'hidden',
              default: 'store-page',
            }
          - { label: 'Title', name: 'title', widget: 'string' }
          - { label: 'Facebook Link', name: 'fbLink', widget: 'string' }
          - {
              name: image,
              label: 'Hero Image',
              widget: image,
              media_library: { config: { multiple: false } },
            }
          - { label: 'Body', name: 'body', widget: 'markdown' }
