backend:
  name: github
  repo: rocket-monkey/hair-core

media_folder: static/img
public_folder: /img

collections:
  - name: 'blog'
    label: 'Blog'
    folder: 'src/pages/blog'
    create: true
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
    fields:
      - {
          label: 'Template Key',
          name: 'templateKey',
          widget: 'hidden',
          default: 'blog-post',
        }
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Publish Date', name: 'date', widget: 'datetime' }
      - { label: 'Description', name: 'description', widget: 'text' }
      - { label: 'Body', name: 'body', widget: 'markdown' }
      - { label: 'Tags', name: 'tags', widget: 'list' }

  - name: 'product'
    label: 'Product'
    folder: 'src/pages/product'
    create: true
    fields:
      - {
          label: 'Template Key',
          name: 'templateKey',
          widget: 'hidden',
          default: 'product-post',
        }
      - { label: 'Title', name: 'title', widget: 'string' }
      - {
          name: image,
          label: 'Product Image',
          widget: image,
          media_library: { config: { multiple: false } },
        }
      - { label: 'Body', name: 'body', widget: 'markdown' }

  - name: openingHours
    label: 'Opening Hours'
    folder: 'src/pages/openingHours'
    create: true
    fields:
      - {
          label: 'Template Key',
          name: 'templateKey',
          widget: 'hidden',
          default: 'openingHours-entry',
        }
      - { name: title, label: Day }
      - { name: hours, label: Hours, required: true }

  - name: 'images'
    label: 'Images'
    files:
      - file: 'src/pages/images/store/index.md'
        label: 'Store'
        name: 'store'
        fields:
          - {
              label: 'Template Key',
              name: 'templateKey',
              widget: 'hidden',
              default: 'images-store',
            }
          - { label: 'Title', name: 'title', widget: 'string' }
          - name: images
            label: 'Images'
            widget: list
            required: false
            fields:
              - {
                  label: image,
                  name: Image,
                  widget: image,
                  media_library: { config: { multiple: false } },
                }

      - file: 'src/pages/images/customers/index.md'
        label: 'Customers'
        name: 'customers'
        fields:
          - {
              label: 'Template Key',
              name: 'templateKey',
              widget: 'hidden',
              default: 'images-customers',
            }
          - { label: 'Title', name: 'title', widget: 'string' }
          - name: images
            label: 'Images'
            widget: list
            required: false
            fields:
              - {
                  label: image,
                  name: Image,
                  widget: image,
                  media_library: { config: { multiple: false } },
                }

      - file: 'src/pages/images/about/index.md'
        label: 'About'
        name: 'about'
        fields:
          - {
              label: 'Template Key',
              name: 'templateKey',
              widget: 'hidden',
              default: 'images-about',
            }
          - { label: 'Title', name: 'title', widget: 'string' }
          - name: images
            label: 'Images'
            widget: list
            required: false
            fields:
              - {
                  label: image,
                  name: Image,
                  widget: image,
                  media_library: { config: { multiple: false } },
                }

  - name: 'pages'
    label: 'Pages'
    files:
      - file: 'src/pages/home/index.md'
        label: 'Home'
        name: 'home'
        fields:
          - {
              label: 'Template Key',
              name: 'templateKey',
              widget: 'hidden',
              default: 'home-page',
            }
          - { label: 'Title', name: 'title', widget: 'string' }
          - { label: 'Body', name: 'body', widget: 'markdown' }

      - file: 'src/pages/about/index.md'
        label: 'About'
        name: 'about'
        fields:
          - {
              label: 'Template Key',
              name: 'templateKey',
              widget: 'hidden',
              default: 'about-page',
            }
          - { label: 'Title', name: 'title', widget: 'string' }
          - {
              name: image,
              label: 'Hero Image',
              widget: image,
              media_library: { config: { multiple: false } },
            }
          - { label: 'Body', name: 'body', widget: 'markdown' }

      - file: 'src/pages/prices/index.md'
        label: 'Prices'
        name: 'prices'
        fields:
          - {
              label: 'Template Key',
              name: 'templateKey',
              widget: 'hidden',
              default: 'prices-page',
            }
          - { label: 'Title', name: 'title', widget: 'string' }
          - { label: 'Facebook Link', name: 'fbLink', widget: 'string' }
          - {
              name: image,
              label: 'Hero Image',
              widget: image,
              media_library: { config: { multiple: false } },
            }
          - { label: 'Body', name: 'body', widget: 'markdown' }

      - file: 'src/pages/appointment/index.md'
        label: 'Appointment'
        name: 'appointment'
        fields:
          - {
              label: 'Template Key',
              name: 'templateKey',
              widget: 'hidden',
              default: 'appointment-page',
            }
          - { label: 'Title', name: 'title', widget: 'string' }
          - {
              name: image,
              label: 'Hero Image',
              widget: image,
              media_library: { config: { multiple: false } },
            }
          - { label: 'Body', name: 'body', widget: 'markdown' }
