backend:
  name: github
  repo: rocket-monkey/jur-gatsby

media_folder: static/img
public_folder: /img

collections:
  - name: 'blog'
    label: 'Blog'
    folder: 'src/pages/blog'
    create: true
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
    fields:
      - {
          label: 'Template Key',
          name: 'templateKey',
          widget: 'hidden',
          default: 'blog-post',
        }
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Publish Date', name: 'date', widget: 'datetime' }
      - { label: 'Description', name: 'description', widget: 'text' }
      - { label: 'Body', name: 'body', widget: 'markdown' }
      - { label: 'Tags', name: 'tags', widget: 'list' }

  - name: event
    label: Event
    folder: 'src/pages/events'
    create: true
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
    fields:
      - {
          label: 'Template Key',
          name: 'templateKey',
          widget: 'hidden',
          default: 'event-post',
        }
      - { name: date, label: Date, widget: date }
      - { name: title, label: Title }
      - {
          name: image,
          label: Image,
          widget: image,
          media_library: { config: { multiple: false } },
        }
      - { name: body, label: Body, widget: markdown }
      - { name: fbLink, label: 'Facebook Link' }
      - {
          label: 'Type',
          name: 'type',
          widget: 'select',
          options: ['vip-session', 'therapy-session', 'golden-age-of-hiphop'],
        }
      - {
          label: 'Location',
          name: 'location',
          widget: 'select',
          options: ['amboss-rampe', 'kiff-aarau'],
        }
      - { name: type, label: Type, widget: hidden, default: event }
      - name: timeTable
        label: 'Time Table'
        widget: list
        required: false
        fields:
          - { label: Act, name: act }
          - { label: Label, name: label }
          - { label: Time, name: time, widget: string, default: '00:00' }

  - name: crew
    label: Crew
    folder: 'src/pages/crew'
    create: true
    fields:
      - {
          label: 'Template Key',
          name: 'templateKey',
          widget: 'hidden',
          default: 'crew-entry',
        }
      - { label: 'Title', name: 'title', widget: 'string' }
      - {
          name: image,
          label: Image,
          widget: image,
          media_library: { config: { multiple: false } },
        }
      - { name: body, label: Body, widget: markdown }
      - {
          name: since,
          label: Since,
          widget: date,
          default: '',
          format: 'DD.MM.YYYY',
        }
      - { name: role, label: Role }
      - { name: soundcloud, label: Soundcloud, required: false }
      - { name: mixcloud, label: Mixcloud, required: false }
      - { name: facebook, label: Facebook, required: false }
      - { name: instagram, label: Instagram, required: false }

  - name: ware
    label: Ware
    folder: 'src/pages/ware'
    create: true
    fields:
      - {
          label: 'Template Key',
          name: 'templateKey',
          widget: 'hidden',
          default: 'ware-entry',
        }
      - { name: title, label: Title }
      - {
          name: image,
          label: Image,
          widget: image,
          media_library: { config: { multiple: false } },
        }
      - { name: body, label: Body, widget: markdown }
      - { name: size, label: Size }
      - { name: gender, label: Gender }

  - name: 'pages'
    label: 'Pages'
    files:
      - file: 'src/pages/home/index.md'
        label: 'Home'
        name: 'home'
        fields:
          - {
              label: 'Template Key',
              name: 'templateKey',
              widget: 'hidden',
              default: 'home-page',
            }
          - { label: 'Title', name: 'title', widget: 'string' }
          - { label: 'Body', name: 'body', widget: 'markdown' }

      - file: 'src/pages/spirit/index.md'
        label: 'Spirit'
        name: 'spirit'
        fields:
          - {
              label: 'Template Key',
              name: 'templateKey',
              widget: 'hidden',
              default: 'spirit-page',
            }
          - { label: 'Title', name: 'title', widget: 'string' }
          - {
              name: image,
              label: 'Hero Image',
              widget: image,
              media_library: { config: { multiple: false } },
            }
          - { label: 'Body', name: 'body', widget: 'markdown' }

      - file: 'src/pages/store/index.md'
        label: 'Store'
        name: 'store'
        fields:
          - {
              label: 'Template Key',
              name: 'templateKey',
              widget: 'hidden',
              default: 'store-page',
            }
          - { label: 'Title', name: 'title', widget: 'string' }
          - { label: 'Facebook Link', name: 'fbLink', widget: 'string' }
          - {
              name: image,
              label: 'Hero Image',
              widget: image,
              media_library: { config: { multiple: false } },
            }
          - { label: 'Body', name: 'body', widget: 'markdown' }
